version: "3.7"
services:
  #outro container --- backend
  springweb:
    container_name: dockerbackend
    build: . #preciso do Dockerfile para gerar a imagem
    image: "gocar"
    ports:
      - "8080:8080"
    networks:
      - servers

    environment:
      - SPRING_PROFILES_ACTIVE=docker

networks:
  servers:
    driver: bridge